# Generated by Django 5.0.4 on 2024-04-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_nextcloud',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
