# Generated by Django 5.0.4 on 2024-04-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
