# Generated by Django 5.0.4 on 2024-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_avatar_url_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
