# Generated by Django 5.0.2 on 2024-03-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='classUnit',
        ),
        migrations.DeleteModel(
            name='ConversionFactor',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
