# Generated by Django 5.0.2 on 2024-03-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_remove_unit_classunit_delete_conversionfactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('symbol', models.CharField(max_length=20, verbose_name='Символ')),
                ('classUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.unitclass')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='ConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(verbose_name='Коэффициент конвертации')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_factors_from', to='sheets.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_factors_to', to='sheets.unit')),
            ],
            options={
                'verbose_name': 'Коэффициент конвертации',
                'verbose_name_plural': 'Коэффициенты конвертации',
            },
        ),
    ]
