# Generated by Django 5.0.2 on 2024-03-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_remove_sheet_material_remove_unit_classunit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sheet',
            new_name='PepperFormat',
        ),
    ]
